In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
s=pd.Series([1,2,3,np.nan,5,6])

In [4]:
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    6.0
dtype: float64


In [9]:
dates=pd.date_range('20180310',periods=6)

In [10]:
print(dates)

DatetimeIndex(['2018-03-10', '2018-03-11', '2018-03-12', '2018-03-13',
               '2018-03-14', '2018-03-15'],
              dtype='datetime64[ns]', freq='D')


In [14]:
arr1 = np.random.rand(2,2,3)
print(arr1)

[[[0.29118032 0.02624149 0.129798  ]
  [0.63610418 0.23877907 0.87584844]]

 [[0.95235267 0.4690856  0.39137957]
  [0.03842681 0.85804106 0.66327777]]]


In [12]:
arr1 = np.random.rand(1,2)
print(arr1)

[[0.80067114 0.07071195]]


In [13]:
arr1 = np.random.rand(3,2)
print(arr1)

[[0.82256798 0.56851124]
 [0.12690868 0.23442817]
 [0.16047159 0.12929286]]


In [15]:
arr1 = np.random.randn(3,2)
print(arr1)

[[ 0.07515204  0.40228684]
 [-0.66540622 -2.19857324]
 [-0.51500443 -0.11925911]]


In [16]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])#生成6行4列位置
print(df)#输出6行4列的表格

                   A         B         C         D
2018-03-10  0.757755  1.057555  0.441792  0.296328
2018-03-11  0.955865  1.270401  1.901318 -0.106970
2018-03-12 -0.329851 -1.636618  0.099336 -0.866593
2018-03-13 -2.066550 -0.783043  0.262192  1.010970
2018-03-14  1.795163  1.050631  2.130463 -0.464893
2018-03-15 -1.095472  0.977519 -0.655248  0.277126


In [17]:
print(df['B'])

2018-03-10    1.057555
2018-03-11    1.270401
2018-03-12   -1.636618
2018-03-13   -0.783043
2018-03-14    1.050631
2018-03-15    0.977519
Freq: D, Name: B, dtype: float64


In [18]:
print(df['B']>0)

2018-03-10     True
2018-03-11     True
2018-03-12    False
2018-03-13    False
2018-03-14     True
2018-03-15     True
Freq: D, Name: B, dtype: bool


In [19]:
print(df[df['B']>0])

                   A         B         C         D
2018-03-10  0.757755  1.057555  0.441792  0.296328
2018-03-11  0.955865  1.270401  1.901318 -0.106970
2018-03-14  1.795163  1.050631  2.130463 -0.464893
2018-03-15 -1.095472  0.977519 -0.655248  0.277126


In [20]:
df_1=pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20180310'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo'
                    })
print(df_1)

     A          B    C  D      E    F
0  1.0 2018-03-10  1.0  3   test  foo
1  1.0 2018-03-10  1.0  3  train  foo
2  1.0 2018-03-10  1.0  3   test  foo
3  1.0 2018-03-10  1.0  3  train  foo


In [21]:
df_1 = pd.Series(1,2,3,4)
print(df_1)

TypeError: Index(...) must be called with a collection of some kind, 2 was passed

In [22]:
df_1 = pd.Series([1,2,3,4])
print(df_1)

0    1
1    2
2    3
3    4
dtype: int64


In [23]:
df_1 = pd.Series([1,2,3,4],index=range(4))
print(df_1)

0    1
1    2
2    3
3    4
dtype: int64
